"""empty message

Revision ID: 550cf3d2c2a8
Revises: 
Create Date: 2019-09-29 02:07:34.343187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550cf3d2c2a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
